import type { StructuralRoleDescriptor, StructuralRoleKind } from './types'

const defineDescriptor = (descriptor: StructuralRoleDescriptor) => descriptor

export const ROLE_TAXONOMY: Record<StructuralRoleKind, StructuralRoleDescriptor> = {
  baseline: defineDescriptor({
    kind: 'baseline',
    family: 'expressionRoot',
    zone: 'center',
    anchor: 'inline',
    shape: 'freeform',
    operatorKind: 'none',
    operandReferenceMode: 'none',
    requiresOperandReference: false,
    allowedOperandRoles: [],
    canOwnScripts: true,
    allowedChildRoles: ['superscript', 'subscript'],
    forbiddenChildRoles: ['numerator', 'denominator', 'fractionBar', 'provisionalFractionBar'],
    peerRoles: ['baseline', 'fractionBar', 'provisionalFractionBar'],
    locality: { local: 1, adjacent: 0.58, distant: 0.22 },
    structuralBarrier: false,
    ancestry: ['expression', 'root'],
    discriminators: ['participates in the main baseline flow', 'can host local script structures'],
  }),
  unsupportedSymbol: defineDescriptor({
    kind: 'unsupportedSymbol',
    family: 'specialSymbol',
    zone: 'center',
    anchor: 'inline',
    shape: 'freeform',
    operatorKind: 'none',
    operandReferenceMode: 'none',
    requiresOperandReference: false,
    allowedOperandRoles: [],
    canOwnScripts: false,
    allowedChildRoles: [],
    forbiddenChildRoles: ['superscript', 'subscript', 'numerator', 'denominator', 'fractionBar', 'provisionalFractionBar', 'baseline', 'enclosureOpen', 'enclosureClose'],
    peerRoles: ['baseline'],
    locality: { local: 0.2, adjacent: 0.1, distant: 0.05 },
    structuralBarrier: false,
    ancestry: ['expression', 'unsupported'],
    discriminators: ['preserved as ink but does not satisfy a supported local structural role', 'used when baseline admissibility is violated without deleting the group'],
  }),
  radical: defineDescriptor({
    kind: 'radical',
    family: 'radicalStructure',
    zone: 'center',
    anchor: 'inline',
    shape: 'freeform',
    operatorKind: 'binaryStructure',
    operandReferenceMode: 'children',
    requiresOperandReference: false,
    allowedOperandRoles: ['baseline'],
    canOwnScripts: true,
    allowedChildRoles: ['superscript', 'subscript'],
    forbiddenChildRoles: ['numerator', 'denominator', 'fractionBar', 'provisionalFractionBar', 'radical'],
    peerRoles: ['baseline', 'fractionBar'],
    locality: { local: 0.94, adjacent: 0.6, distant: 0.14 },
    structuralBarrier: true,
    ancestry: ['expression', 'radical', 'operator'],
    discriminators: ['hosts a radicand region to its right interior', 'can optionally host an upper-left index', 'can still host outer scripts as a whole expression'],
  }),
  provisionalFractionBar: defineDescriptor({
    kind: 'provisionalFractionBar',
    family: 'fractionStructure',
    zone: 'lower',
    anchor: 'centered',
    shape: 'horizontalLine',
    operatorKind: 'binaryStructure',
    operandReferenceMode: 'children',
    requiresOperandReference: false,
    allowedOperandRoles: ['numerator', 'denominator'],
    canOwnScripts: false,
    allowedChildRoles: ['numerator', 'denominator'],
    forbiddenChildRoles: ['superscript', 'subscript', 'fractionBar', 'provisionalFractionBar', 'baseline'],
    peerRoles: ['baseline', 'fractionBar'],
    locality: { local: 0.9, adjacent: 0.66, distant: 0.08 },
    structuralBarrier: true,
    ancestry: ['expression', 'fraction', 'operator', 'provisional'],
    discriminators: ['line-like enough to be a fraction candidate', 'can persist while operand evidence is incomplete', 'upgrades to fractionBar once numerator and denominator jointly reinforce it'],
  }),
  superscript: defineDescriptor({
    kind: 'superscript',
    family: 'script',
    zone: 'upper',
    anchor: 'right',
    shape: 'freeform',
    operatorKind: 'unaryReference',
    operandReferenceMode: 'parent',
    requiresOperandReference: true,
    allowedOperandRoles: ['baseline', 'numerator', 'denominator', 'superscript'],
    canOwnScripts: true,
    allowedChildRoles: ['superscript'],
    forbiddenChildRoles: ['subscript', 'numerator', 'denominator', 'fractionBar', 'provisionalFractionBar'],
    peerRoles: ['subscript'],
    locality: { local: 1, adjacent: 0.52, distant: 0.16 },
    structuralBarrier: false,
    ancestry: ['expression', 'script', 'upperScript'],
    discriminators: ['prefers above-right placement', 'can only host another superscript, never a subscript'],
  }),
  subscript: defineDescriptor({
    kind: 'subscript',
    family: 'script',
    zone: 'lower',
    anchor: 'right',
    shape: 'freeform',
    operatorKind: 'unaryReference',
    operandReferenceMode: 'parent',
    requiresOperandReference: true,
    allowedOperandRoles: ['baseline', 'numerator', 'denominator', 'subscript'],
    canOwnScripts: true,
    allowedChildRoles: ['subscript'],
    forbiddenChildRoles: ['superscript', 'numerator', 'denominator', 'fractionBar', 'provisionalFractionBar'],
    peerRoles: ['superscript'],
    locality: { local: 1, adjacent: 0.52, distant: 0.16 },
    structuralBarrier: false,
    ancestry: ['expression', 'script', 'lowerScript'],
    discriminators: ['prefers below-right placement', 'can only host another subscript, never a superscript'],
  }),
  numerator: defineDescriptor({
    kind: 'numerator',
    family: 'fractionMember',
    zone: 'upper',
    anchor: 'centered',
    shape: 'freeform',
    operatorKind: 'none',
    operandReferenceMode: 'none',
    requiresOperandReference: false,
    allowedOperandRoles: [],
    canOwnScripts: true,
    allowedChildRoles: ['superscript', 'subscript'],
    forbiddenChildRoles: ['numerator', 'denominator', 'fractionBar', 'provisionalFractionBar'],
    peerRoles: ['denominator'],
    locality: { local: 1, adjacent: 0.64, distant: 0.2 },
    structuralBarrier: false,
    ancestry: ['expression', 'fraction', 'member', 'upperMember'],
    discriminators: ['sits above a fraction bar', 'prefers horizontal centering with the bar'],
  }),
  denominator: defineDescriptor({
    kind: 'denominator',
    family: 'fractionMember',
    zone: 'lower',
    anchor: 'centered',
    shape: 'freeform',
    operatorKind: 'none',
    operandReferenceMode: 'none',
    requiresOperandReference: false,
    allowedOperandRoles: [],
    canOwnScripts: true,
    allowedChildRoles: ['superscript', 'subscript'],
    forbiddenChildRoles: ['numerator', 'denominator', 'fractionBar', 'provisionalFractionBar'],
    peerRoles: ['numerator'],
    locality: { local: 0.9, adjacent: 0.54, distant: 0.18 },
    structuralBarrier: false,
    ancestry: ['expression', 'fraction', 'member', 'lowerMember'],
    discriminators: ['sits below a fraction bar', 'prefers horizontal centering with the bar'],
  }),
  fractionBar: defineDescriptor({
    kind: 'fractionBar',
    family: 'fractionStructure',
    zone: 'lower',
    anchor: 'centered',
    shape: 'horizontalLine',
    operatorKind: 'binaryStructure',
    operandReferenceMode: 'children',
    requiresOperandReference: true,
    allowedOperandRoles: ['numerator', 'denominator'],
    canOwnScripts: false,
    allowedChildRoles: ['numerator', 'denominator'],
    forbiddenChildRoles: ['superscript', 'subscript', 'fractionBar', 'provisionalFractionBar', 'baseline'],
    peerRoles: ['baseline'],
    locality: { local: 1, adjacent: 0.72, distant: 0.08 },
    structuralBarrier: true,
    ancestry: ['expression', 'fraction', 'operator'],
    discriminators: ['must be line-like', 'prefers directly centered content above and below', 'prefers width comparable to the immediately above member span'],
  }),
  enclosureOpen: defineDescriptor({
    kind: 'enclosureOpen',
    family: 'enclosureStructure',
    zone: 'center',
    anchor: 'inline',
    shape: 'freeform',
    operatorKind: 'none',
    operandReferenceMode: 'none',
    requiresOperandReference: false,
    allowedOperandRoles: [],
    canOwnScripts: false,
    allowedChildRoles: [],
    forbiddenChildRoles: ['superscript', 'subscript', 'numerator', 'denominator', 'fractionBar', 'provisionalFractionBar', 'baseline', 'enclosureOpen', 'enclosureClose'],
    peerRoles: ['enclosureClose', 'baseline'],
    locality: { local: 1, adjacent: 0.66, distant: 0.08 },
    structuralBarrier: true,
    ancestry: ['expression', 'enclosure', 'boundary', 'open'],
    discriminators: ['anchors the left side of a local enclosure', 'does not host scripts or fraction members directly'],
  }),
  enclosureClose: defineDescriptor({
    kind: 'enclosureClose',
    family: 'enclosureStructure',
    zone: 'center',
    anchor: 'inline',
    shape: 'freeform',
    operatorKind: 'none',
    operandReferenceMode: 'none',
    requiresOperandReference: false,
    allowedOperandRoles: [],
    canOwnScripts: false,
    allowedChildRoles: [],
    forbiddenChildRoles: ['superscript', 'subscript', 'numerator', 'denominator', 'fractionBar', 'provisionalFractionBar', 'baseline', 'enclosureOpen', 'enclosureClose'],
    peerRoles: ['enclosureOpen', 'baseline'],
    locality: { local: 1, adjacent: 0.66, distant: 0.08 },
    structuralBarrier: true,
    ancestry: ['expression', 'enclosure', 'boundary', 'close'],
    discriminators: ['anchors the right side of a local enclosure', 'does not host scripts or fraction members directly'],
  }),
}

export const getRoleDescriptor = (kind: StructuralRoleKind) => ROLE_TAXONOMY[kind]

export const roleCanOwnScripts = (kind: StructuralRoleKind) => ROLE_TAXONOMY[kind].canOwnScripts

export const roleRequiresOperandReference = (kind: StructuralRoleKind) => ROLE_TAXONOMY[kind].requiresOperandReference

export const roleUsesParentOperand = (kind: StructuralRoleKind) => ROLE_TAXONOMY[kind].operandReferenceMode === 'parent'

export const roleUsesChildOperands = (kind: StructuralRoleKind) => ROLE_TAXONOMY[kind].operandReferenceMode === 'children'

export const roleAllowsOperandRole = (operatorRole: StructuralRoleKind, operandRole: StructuralRoleKind) => {
  const descriptor = ROLE_TAXONOMY[operatorRole]
  return descriptor.allowedOperandRoles.includes(operandRole)
}

export const roleAllowsChildRole = (parentRole: StructuralRoleKind, childRole: StructuralRoleKind) => {
  const descriptor = ROLE_TAXONOMY[parentRole]
  if (descriptor.forbiddenChildRoles.includes(childRole)) return false
  return descriptor.allowedChildRoles.includes(childRole)
}

export const getRoleLocalityBias = (kind: StructuralRoleKind) => ROLE_TAXONOMY[kind].locality