-- Extend user profile to capture full enrolment details
ALTER TABLE "User"
  ADD COLUMN "firstName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "lastName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "middleNames" TEXT,
  ADD COLUMN "dateOfBirth" TIMESTAMP(3),
  ADD COLUMN "phoneNumber" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "alternatePhone" TEXT,
  ADD COLUMN "recoveryEmail" TEXT,
  ADD COLUMN "emergencyContactName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "emergencyContactRelationship" TEXT,
  ADD COLUMN "emergencyContactPhone" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "addressLine1" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "addressLine2" TEXT,
  ADD COLUMN "city" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "province" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "postalCode" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "country" TEXT NOT NULL DEFAULT 'South Africa',
  ADD COLUMN "schoolName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "idNumber" TEXT,
  ADD COLUMN "consentToPolicies" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "consentTimestamp" TIMESTAMP(3),
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "avatar" TEXT;
